-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 10:06:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy` DEFAULT CHARACTER SET utf8 ;
USE `paymybuddy` ;

-- -----------------------------------------------------
-- Table `paymybuddy`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`User` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `iban` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `iban_UNIQUE` (`iban` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`User_to_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`User_to_user` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`User_to_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `ami` INT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `ami_idx` (`ami` ASC) VISIBLE,
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `ami_UNIQUE` (`ami` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_to_user_ami`
    FOREIGN KEY (`ami`)
    REFERENCES `paymybuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_to_user_user`
    FOREIGN KEY (`user`)
    REFERENCES `paymybuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`Transaction_interne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`Transaction_interne` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`Transaction_interne` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL,
  `crediteur` INT NOT NULL,
  `debiteur` INT NOT NULL,
  `commission` DECIMAL(10,2) NULL,
  INDEX `crediteur_idx` (`crediteur` ASC) VISIBLE,
  INDEX `debiteur_idx` (`debiteur` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `transaction_interne_crediteur`
    FOREIGN KEY (`crediteur`)
    REFERENCES `paymybuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transaction_interne_debiteur`
    FOREIGN KEY (`debiteur`)
    REFERENCES `paymybuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`Application` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`Application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `montant` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`Transaction_externe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`Transaction_externe` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`Transaction_externe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `montant` DECIMAL(10,2) NULL,
  `user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `transation_externe_user`
    FOREIGN KEY (`user`)
    REFERENCES `paymybuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
